Add fetch stage logic.
quantiumv/core pull request #3
Opened 2023-11-04 09:32 UTC by bitglitcher

This is preliminary logic. Still has some bugs in the stall_ff signal.

2023-11-04 14:40 UTC, siddhpant requested changes
Quartus gives 45 warnings among other things.

<details>

<summary>Quartus log</summary>

```
Info: *******************************************************************
Info: Running Quartus Prime Analysis & Synthesis
	Info: Version 21.1.0 Build 842 10/21/2021 SJ Lite Edition
	Info: Processing started: Sat Nov  4 20:07:54 2023
Info: Command: quartus_map --read_settings_files=on --write_settings_files=off fetch_stage -c fetch_stage
Info (20030): Parallel compilation is enabled and will use 12 of the 12 processors detected
Info (12021): Found 1 design units, including 1 entities, in source file /home/yoojer/Codecel/QuantiumV/core/src/fetch_stage.sv
	Info (12023): Found entity 1: fetch_stage
Info (12127): Elaborating entity "fetch_stage" for the top level hierarchy
Warning (10036): Verilog HDL or VHDL warning at fetch_stage.sv(86): object "hit" assigned a value but never read
Warning (10027): Verilog HDL or VHDL warning at the fetch_stage.sv(109): index expression is not wide enough to address all of the elements in the array
Warning (10240): Verilog HDL Always Construct warning at fetch_stage.sv(115): inferring latch(es) for variable "DAT_O", which holds its previous value in one or more paths through the always construct
Warning (10240): Verilog HDL Always Construct warning at fetch_stage.sv(115): inferring latch(es) for variable "CTI_O", which holds its previous value in one or more paths through the always construct
Warning (10240): Verilog HDL Always Construct warning at fetch_stage.sv(115): inferring latch(es) for variable "WE_O", which holds its previous value in one or more paths through the always construct
Info (10041): Inferred latch for "WE_O" at fetch_stage.sv(115)
Info (10041): Inferred latch for "CTI_O[0]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "CTI_O[1]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "CTI_O[2]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[0]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[1]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[2]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[3]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[4]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[5]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[6]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[7]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[8]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[9]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[10]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[11]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[12]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[13]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[14]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[15]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[16]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[17]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[18]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[19]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[20]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[21]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[22]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[23]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[24]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[25]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[26]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[27]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[28]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[29]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[30]" at fetch_stage.sv(115)
Info (10041): Inferred latch for "DAT_O[31]" at fetch_stage.sv(115)
Warning (13024): Output pins are stuck at VCC or GND
	Warning (13410): Pin "DAT_O[0]" is stuck at GND
	Warning (13410): Pin "DAT_O[1]" is stuck at GND
	Warning (13410): Pin "DAT_O[2]" is stuck at GND
	Warning (13410): Pin "DAT_O[3]" is stuck at GND
	Warning (13410): Pin "DAT_O[4]" is stuck at GND
	Warning (13410): Pin "DAT_O[5]" is stuck at GND
	Warning (13410): Pin "DAT_O[6]" is stuck at GND
	Warning (13410): Pin "DAT_O[7]" is stuck at GND
	Warning (13410): Pin "DAT_O[8]" is stuck at GND
	Warning (13410): Pin "DAT_O[9]" is stuck at GND
	Warning (13410): Pin "DAT_O[10]" is stuck at GND
	Warning (13410): Pin "DAT_O[11]" is stuck at GND
	Warning (13410): Pin "DAT_O[12]" is stuck at GND
	Warning (13410): Pin "DAT_O[13]" is stuck at GND
	Warning (13410): Pin "DAT_O[14]" is stuck at GND
	Warning (13410): Pin "DAT_O[15]" is stuck at GND
	Warning (13410): Pin "DAT_O[16]" is stuck at GND
	Warning (13410): Pin "DAT_O[17]" is stuck at GND
	Warning (13410): Pin "DAT_O[18]" is stuck at GND
	Warning (13410): Pin "DAT_O[19]" is stuck at GND
	Warning (13410): Pin "DAT_O[20]" is stuck at GND
	Warning (13410): Pin "DAT_O[21]" is stuck at GND
	Warning (13410): Pin "DAT_O[22]" is stuck at GND
	Warning (13410): Pin "DAT_O[23]" is stuck at GND
	Warning (13410): Pin "DAT_O[24]" is stuck at GND
	Warning (13410): Pin "DAT_O[25]" is stuck at GND
	Warning (13410): Pin "DAT_O[26]" is stuck at GND
	Warning (13410): Pin "DAT_O[27]" is stuck at GND
	Warning (13410): Pin "DAT_O[28]" is stuck at GND
	Warning (13410): Pin "DAT_O[29]" is stuck at GND
	Warning (13410): Pin "DAT_O[30]" is stuck at GND
	Warning (13410): Pin "DAT_O[31]" is stuck at GND
	Warning (13410): Pin "CTI_O[0]" is stuck at GND
	Warning (13410): Pin "CTI_O[1]" is stuck at GND
	Warning (13410): Pin "CTI_O[2]" is stuck at GND
	Warning (13410): Pin "WE_O" is stuck at GND
Info (286030): Timing-Driven Synthesis is running
Info (17049): 9 registers lost all their fanouts during netlist optimizations.
Info (144001): Generated suppressed messages file /home/yoojer/Codecel/QuantiumV/quartus/fetch_stage/output_files/fetch_stage.map.smsg
Info (16010): Generating hard_block partition "hard_block:auto_generated_inst"
	Info (16011): Adding 0 node(s), including 0 DDIO, 0 PLL, 0 transceiver and 0 LCELL
Warning (21074): Design contains 2 input pin(s) that do not drive logic
	Warning (15610): No output dependent on input pin "ERR_I"
	Warning (15610): No output dependent on input pin "RTY_I"
Info (21057): Implemented 430 device resources after synthesis - the final resource count might be different
	Info (21058): Implemented 70 input pins
	Info (21059): Implemented 135 output pins
	Info (21061): Implemented 225 logic cells
Info: Quartus Prime Analysis & Synthesis was successful. 0 errors, 45 warnings
	Info: Peak virtual memory: 535 megabytes
	Info: Processing ended: Sat Nov  4 20:08:01 2023
	Info: Elapsed time: 00:00:07
	Info: Total CPU time (on all processors): 00:00:17
```

</details>

2023-11-04 14:40 UTC, siddhpant commented on src/fetch_stage.sv
> +    input  logic ACK_I,
It should be `i_ack`. Same for others.

2023-11-04 14:40 UTC, siddhpant commented on src/fetch_stage.sv
> +    output logic [31:0] ADR_O,
`o_adr` or rather, the more descriptive `o_address`.

2023-11-04 14:40 UTC, siddhpant commented on src/fetch_stage.sv
> +wire hit;
As we are using SV

s/wire/logic

s/reg/logic

2023-11-04 14:40 UTC, siddhpant commented on src/fetch_stage.sv
> +    output logic [31:0] ADR_O,
Macro from defaults should be used. defaults.sv has `WORD_SIZE`. See https://github.com/quantiumv/core/blob/22ea951559370be6ed99215b1a343f9d31053e75/src/decoder.sv#L132 for example.

2023-11-05 09:03 UTC, bitglitcher commented on src/fetch_stage.sv
> +    output logic [31:0] ADR_O,
Those names are how signals are named in the Wishbone spec.

2023-11-05 09:05 UTC, bitglitcher commented on src/fetch_stage.sv
> +wire hit;
It shouldn't be an issue. It's not a requirement to use logic as type on everything.

2023-11-05 09:06 UTC, bitglitcher commented on src/fetch_stage.sv
> +    output logic [31:0] ADR_O,
Why do we need a macro to define the size of word? Sizes: Byte: 1, Half Word: 2, Word: 4, a DWord 8.

2023-11-05 09:08 UTC, bitglitcher commented
> Quartus gives a couple of warnings among other things.
> 
> Quartus log

Those warning come from assigning those signals to 0 and never changing their value. It should be good for now since we don't have any write back logic implemented. We don't need to set DAT_O or CTI_O to anything yet.

2023-11-05 09:33 UTC, siddhpant commented on src/fetch_stage.sv
> +    output logic [31:0] ADR_O,
Oh okay. Then it should be something like `i_wb_master_rty`.

Goal is to have the variable name describe itself as accurately as it can, so when reading code the logic will be immediately clear (what goes where), which helps in maintenance. So we should not shy away from longer names.

Currently, one has to be sure it is the master interface by reading the comment above it. The variable identifier itself doesn't convey the information.

2023-11-05 09:55 UTC, siddhpant commented on src/fetch_stage.sv
> +wire hit;
We should use newer language features where possible.

`logic` is meant to replace `reg`, and provides additional security like preventing multiple drivers, and you get error during simulation itself.

![image](https://github.com/quantiumv/core/assets/25429745/496c62b7-39aa-4ded-ac4a-a8b7d2164c90)

(From SV spec)

While `wire` isn't the same, (it is a 4-valued signal type with multiple drivers), but using `logic` will be inferred appropriately while disallowing multiple driver.

2023-11-05 09:56 UTC, siddhpant commented on src/fetch_stage.sv
> +    output logic [31:0] ADR_O,
For abstraction. Currently, `WORD_SIZE` is 32. But we may one day want to change to rv64.

Also it allows the code to be generic.

2024-03-29 16:51 UTC, merged